development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: paper_cups_development
  pool: 5
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: paper_cups_test
  pool: 5
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: paper_cups_production
  pool: 5