development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: camping-gas_development
  pool: 5
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: camping-gas_test
  pool: 5
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: camping-gas_production
  pool: 5